// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEih8b0OKPvDSpbRt4s-cRdV8IT39w9dg',
    appId: '1:1022135696411:web:6fb4a830a56bfbc2bf8cbe',
    messagingSenderId: '1022135696411',
    projectId: 'creativa2026creativa2026-2842f',
    authDomain: 'creativa2026creativa2026-2842f.firebaseapp.com',
    storageBucket: 'creativa2026creativa2026-2842f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqs0Og-ViaiJe1tv95kpY5S5sIFjbYVsg',
    appId: '1:1022135696411:android:42d0f511396c33d6bf8cbe',
    messagingSenderId: '1022135696411',
    projectId: 'creativa2026creativa2026-2842f',
    storageBucket: 'creativa2026creativa2026-2842f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNdYddsVMlqKt5sIIhsELH0NSz-ypjnFs',
    appId: '1:1022135696411:ios:3ead3d01580e1a06bf8cbe',
    messagingSenderId: '1022135696411',
    projectId: 'creativa2026creativa2026-2842f',
    storageBucket: 'creativa2026creativa2026-2842f.firebasestorage.app',
    iosBundleId: 'com.example.task6NodeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNdYddsVMlqKt5sIIhsELH0NSz-ypjnFs',
    appId: '1:1022135696411:ios:3ead3d01580e1a06bf8cbe',
    messagingSenderId: '1022135696411',
    projectId: 'creativa2026creativa2026-2842f',
    storageBucket: 'creativa2026creativa2026-2842f.firebasestorage.app',
    iosBundleId: 'com.example.task6NodeFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEih8b0OKPvDSpbRt4s-cRdV8IT39w9dg',
    appId: '1:1022135696411:web:5b955dc3b6ddda04bf8cbe',
    messagingSenderId: '1022135696411',
    projectId: 'creativa2026creativa2026-2842f',
    authDomain: 'creativa2026creativa2026-2842f.firebaseapp.com',
    storageBucket: 'creativa2026creativa2026-2842f.firebasestorage.app',
  );
}
